#pragma once
#include "bftTypedefs.h"

namespace bft {

    void simpleUmat( Eigen::Ref<Matrix6>                      abqC,
                     Eigen::Ref<Vector6>                      abqStress,
                     Eigen::Ref<Eigen::VectorXd>              abqStateVars,
                     const Eigen::Ref<const bft::Vector6>&    abqStrain,
                     const Eigen::Ref<const bft::Vector6>&    abqDStrain,
                     const Eigen::Ref<const Eigen::VectorXd>& matProps,
                     double&                                  pNewdT,
                     double                                   charElemlen,
                     const double                             time[2],
                     double                                   dT,
                     int                                      noEl,
                     int                                      noGaussPt,
                     pUmatType                                umatPointer );

    void simpleUmatNonLocal( Eigen::Ref<Matrix6>                      dStressdStrain,
                             Eigen::Ref<Vector6>                      stress,
                             double&                                  intParamLocal,
                             Eigen::Ref<Vector6>                      dStressDIntParamNonlocal,
                             Eigen::Ref<Vector6>                      dIntParamLocalDStrain,
                             double&                                  nonLocalRadius,
                             Eigen::Ref<Eigen::VectorXd>              stateVars,
                             const Eigen::Ref<const bft::Vector6>&    strainOld,
                             const Eigen::Ref<const bft::Vector6>&    dStrain,
                             double                                   intParamNonLocalOld,
                             double                                   dIntParamNonLocal,
                             const Eigen::Ref<const Eigen::VectorXd>& matProps,
                             double&                                  pNewdT,
                             const double                             time[2],
                             double                                   dT,
                             int                                      noEl,
                             int                                      noGaussPt,
                             pUmatType                                umatPointer );

    void umatPlaneStress( Eigen::Ref<Matrix6>                      dStressdStrain,
                          Eigen::Ref<Vector6>                      stress,
                          Eigen::Ref<Eigen::VectorXd>              stateVars,
                          const Eigen::Ref<const bft::Vector6>&    strain,
                          Eigen::Ref<Vector6>                      dStrain,
                          const Eigen::Ref<const Eigen::VectorXd>& matProps,
                          double&                                  pNewdT,
                          double                                   charElemlen,
                          const double                             time[2],
                          double                                   dT,
                          int                                      noEl,
                          int                                      noGaussPt,
                          pUmatType                                umatPointer );

    void simpleUmatPlaneStressNonLocal( Eigen::Ref<Matrix6>                      dStressdStrain,
                                        Eigen::Ref<Vector6>                      stress,
                                        double&                                  intParamLocal,
                                        Eigen::Ref<Vector6>                      dStressDIntParamNonlocal,
                                        Eigen::Ref<Vector6>                      dIntParamLocalDStrain,
                                        double&                                  nonLocalRadius,
                                        Eigen::Ref<Eigen::VectorXd>              stateVars,
                                        const Eigen::Ref<const bft::Vector6>&    strainOld,
                                        Eigen::Ref<Eigen::VectorXd>              dStrain,
                                        double                                   intParamNonLocalOld,
                                        double                                   dIntParamNonLocal,
                                        const Eigen::Ref<const Eigen::VectorXd>& matProps,
                                        double&                                  pNewdT,
                                        const double                             time[2],
                                        double                                   dT,
                                        int                                      noEl,
                                        int                                      noGaussPt,
                                        pUmatType                                umatPointer );

    void umatPlaneStressBisectionMethod( Eigen::Ref<Matrix6>                      Cep,
                                         Eigen::Ref<Vector6>                      stress,
                                         Eigen::Ref<Eigen::VectorXd>              stateVars,
                                         const Eigen::Ref<const bft::Vector6>&    strain,
                                         Eigen::Ref<Vector6>                      dStrain,
                                         const Eigen::Ref<const Eigen::VectorXd>& matProps,
                                         double&                                  pNewdT,
                                         double                                   charElemlen,
                                         const double                             time[2],
                                         double                                   dT,
                                         int                                      noEl,
                                         int                                      noGaussPt,
                                         pUmatType                                umatPointer );

    void umatPlaneStressBisectionMethodNonLocal( Eigen::Ref<Matrix6>                      dStressdStrain,
                                                 Eigen::Ref<Vector6>                      stress,
                                                 double&                                  intParamLocal,
                                                 Eigen::Ref<Vector6>                      dStressDIntParamNonlocal,
                                                 Eigen::Ref<Vector6>                      dIntParamLocalDStrain,
                                                 double&                                  nonLocalRadius,
                                                 Eigen::Ref<Eigen::VectorXd>              stateVars,
                                                 const Eigen::Ref<const bft::Vector6>&    strainOld,
                                                 Eigen::Ref<Eigen::VectorXd>              dStrain,
                                                 double                                   intParamNonLocalOld,
                                                 double                                   dIntParamNonLocal,
                                                 const Eigen::Ref<const Eigen::VectorXd>& matProps,
                                                 double&                                  pNewdT,
                                                 const double                             time[2],
                                                 double                                   dT,
                                                 int                                      noEl,
                                                 int                                      noGaussPt,
                                                 pUmatType                                umatPointer );
} // namespace bft
