#pragma once 
#include "bftTypedefs.h"

namespace bft{

	void simpleUmat(Ref<Matrix6> abqC,
                    Ref<Vector6> abqStress,
                    Ref<VectorXd> abqStateVars,
                    const  Ref<const Vector6>& abqStrain,
                    const  Ref<const Vector6>& abqDStrain,
                    const  Ref<const Eigen::VectorXd>& matProps,
                    double& pNewdT,
                    double charElemlen,
                    const double time[2],
                    double dT,
                    int noEl,
                    int noGaussPt,
                    pUmatType umatPointer);

	void simpleUmatNonLocal(Ref<Matrix6>                        dStressdStrain,
                            Ref<Vector6>                        stress,
                            double&                             intParamLocal,
                            Ref<Vector6>                        dStressDIntParamNonlocal,
                            Ref<Vector6>                        dIntParamLocalDStrain,
                            double&                             nonLocalRadius,
                            Ref<VectorXd>                       stateVars,
                            const  Ref<const Vector6>&          strainOld,
                            const  Ref<const Vector6>&          dStrain,
                            double                              intParamNonLocalOld,
                            double                              dIntParamNonLocal,
                            const  Ref<const VectorXd>&         matProps,
                            double&                             pNewdT,
                            const double                        time[2],
                            double                              dT,
                            int                                 noEl,
                            int                                 noGaussPt,
                            pUmatType                           umatPointer);

    void umatPlaneStress(	Ref<Matrix6> dStressdStrain,
	                        Ref<Vector6> stress,
                            Ref<VectorXd> stateVars,
	                        const Ref<const Vector6>& strain,
	                        Ref<Vector6> dStrain,
                            const Ref<const VectorXd>& matProps,
                            double& pNewdT,
                            double charElemlen,
                            const double time[2],
                            double dT,
	                        int noEl,
                            int noGaussPt,
                            pUmatType umatPointer);

	void simpleUmatPlaneStressNonLocal(
                            Ref<Matrix6>                        dStressdStrain,
                            Ref<Vector6>                        stress,
                            double&                             intParamLocal,
                            Ref<Vector6>                        dStressDIntParamNonlocal,
                            Ref<Vector6>                        dIntParamLocalDStrain,
                            double&                             nonLocalRadius,
                            Ref<VectorXd>                       stateVars,
                            const  Ref<const Vector6>&          strainOld,
                            Ref<VectorXd>                       dStrain,
                            double                              intParamNonLocalOld,
                            double                              dIntParamNonLocal,
                            const  Ref<const VectorXd>&         matProps,
                            double&                             pNewdT,
                            const double                        time[2],
                            double                              dT,
                            int                                 noEl,
                            int                                 noGaussPt, 
                            pUmatType                           umatPointer);

    void umatPlaneStressBisectionMethod (Ref<Matrix6> Cep,
	                        Ref<Vector6> stress,
                            Ref<VectorXd> stateVars,
	                        const Ref<const Vector6>& strain,
	                        Ref<Vector6> dStrain,
                            const Ref<const VectorXd>& matProps,
                            double& pNewdT,
                            double charElemlen,
                            const double time[2],
                            double dT,
	                        int noEl,
                            int noGaussPt,
                            pUmatType umatPointer);

    void umatPlaneStressBisectionMethodNonLocal(
                                Ref<Matrix6>                        dStressdStrain,
                                Ref<Vector6>                        stress,
                                double&                             intParamLocal,
                                Ref<Vector6>                        dStressDIntParamNonlocal,
                                Ref<Vector6>                        dIntParamLocalDStrain,
                                double&                             nonLocalRadius,
                                Ref<VectorXd>                       stateVars,
                                const  Ref<const Vector6>&          strainOld,
                                Ref<VectorXd>                       dStrain,
                                double                              intParamNonLocalOld,
                                double                              dIntParamNonLocal,
                                const  Ref<const VectorXd>&         matProps,
                                double&                             pNewdT,
                                const double                        time[2],
                                double                              dT,
                                int                                 noEl,
                                int                                 noGaussPt, 
                                pUmatType                           umatPointer) ;
}
